// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using UserManagement.Data;

#nullable disable
#pragma warning disable CA1814

namespace UserManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UserManagement.Models.User", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("City").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<DateTime>("DateOfBirth").HasColumnType("datetime2");
                b.Property<string>("Email").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<string>("FirstName").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("Gender").IsRequired().HasMaxLength(10).HasColumnType("nvarchar(10)");
                b.Property<string>("LastName").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("MobileNo").IsRequired().HasMaxLength(10).HasColumnType("nvarchar(10)");
                b.Property<string>("PhotoPath").HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<string>("ProfessionalSkills").IsRequired().HasMaxLength(500).HasDefaultValue("").HasColumnType("nvarchar(500)");

                b.HasKey("Id");
                b.ToTable("Users");

                b.HasData(
                    new { Id = 1, FirstName = "Rajesh",  LastName = "Sharma", Gender = "Male",
                          Email = "rajesh.sharma@example.com",  MobileNo = "9876543210",
                          DateOfBirth = new DateTime(1995,6,15), City = "Pune",
                          ProfessionalSkills = "Communication,Problem Solving", PhotoPath = (string)null },
                    new { Id = 2, FirstName = "Priya", LastName = "Patel", Gender = "Female",
                          Email = "priya.patel@example.com", MobileNo = "9123456780",
                          DateOfBirth = new DateTime(1998,3,22), City = "Mumbai",
                          ProfessionalSkills = "Communication,Critical Thinking,Initiative", PhotoPath = (string)null }
                );
            });
#pragma warning restore 612, 618
        }
    }
}
